import React from 'react';
import { Card } from '../components/ui/card';
import { FileText } from 'lucide-react';
import { useLanguage } from '../i18n';

export default function Terms() {
  const { lang } = useLanguage();

  const content = {
    en: {
      title: 'Terms of Use',
      subtitle: 'The terms and conditions governing your use of Avenia services.',
      updated: 'March 08, 2026',
      sections: [
        {
          title: '1. Scope of Service',
          paragraphs: [
            'Avenia is an AI-powered platform that provides chat, image/video generation, document summarization, and speech workflows. By using these services you agree to the terms outlined in this document.'
          ],
        },
        {
          title: '2. User Responsibilities',
          paragraphs: ['As a user you agree to:'],
          list: [
            'Use the platform only for lawful purposes.',
            'Avoid uploading content that infringes intellectual property rights.',
            'Refrain from distributing malware, spam, or harmful content.',
            'Respect the rights of other users.',
            'Keep your account credentials secure.'
          ],
        },
        {
          title: '3. AI Usage & Third‑Party Providers',
          paragraphs: [
            'Avenia uses third‑party AI services to deliver features. Chat and document processing may use Google Gemini. Image/video generation may use fal.ai and/or Gemini.',
            'AI outputs are generated by algorithms and may be inaccurate. You agree not to rely solely on AI for critical decisions.'
          ],
        },
        {
          title: '4. Data Processing & Privacy',
          paragraphs: [
            'Uploaded content is processed to deliver the requested service. For details, please review our Privacy Policy.'
          ],
          link: {
            text: 'Privacy Policy',
            href: '/privacy'
          }
        },
        {
          title: '5. Subscriptions & Payments',
          paragraphs: [
            'Premium subscriptions are billed through Google Play. You can cancel at any time via Google Play → Account → Payments & Subscriptions.',
            'Refund requests are evaluated according to Google Play policies.'
          ],
        },
        {
          title: '6. Intellectual Property',
          paragraphs: [
            'Avenia and associated content are protected by intellectual property laws. You represent that you own or have permission to use any content you upload.'
          ],
        },
        {
          title: '7. Service Limitations',
          paragraphs: [
            'The service may have usage limits, file size limits, and temporary outages due to maintenance or unforeseen circumstances.'
          ],
        },
        {
          title: '8. Changes',
          paragraphs: [
            'These terms may be updated periodically. Continued use of the service after changes take effect constitutes acceptance of the revised terms.'
          ],
        },
        {
          title: '9. Contact',
          paragraphs: [
            'If you have questions about these terms, contact us at support@aveniaichat.com.'
          ],
        }
      ],
      footerNote: '📄 By accepting these terms you help keep Avenia safe and fair for everyone.'
    },
    tr: {
      title: 'Kullanım Şartları',
      subtitle: 'Avenia hizmetlerini kullanım koşullarını açıklar.',
      updated: '08 Mart 2026',
      sections: [
        {
          title: '1. Hizmet Kapsamı',
          paragraphs: [
            'Avenia; sohbet, görsel/video üretimi, belge özeti ve konuşma iş akışları sunan yapay zeka destekli bir platformdur. Bu hizmetleri kullanarak bu şartları kabul etmiş olursunuz.'
          ],
        },
        {
          title: '2. Kullanıcı Sorumlulukları',
          paragraphs: ['Kullanıcı olarak şunları kabul edersiniz:'],
          list: [
            'Platformu yalnızca yasal amaçlarla kullanmak.',
            'Telif haklarını ihlal eden içerik yüklememek.',
            'Zararlı içerik, spam veya kötüye kullanım yapmamak.',
            'Diğer kullanıcıların haklarına saygı göstermek.',
            'Hesap bilgilerinizi güvenli tutmak.'
          ],
        },
        {
          title: '3. AI Kullanımı ve Üçüncü Taraf Sağlayıcılar',
          paragraphs: [
            'Avenia, özellikleri sağlamak için üçüncü taraf AI servisleri kullanabilir. Sohbet ve belge işleme Google Gemini ile, görsel/video üretimi fal.ai ve/veya Gemini ile yapılabilir.',
            'AI çıktıları hatalı olabilir. Kritik kararlar için yalnızca AI çıktısına güvenmemelisiniz.'
          ],
        },
        {
          title: '4. Veri İşleme ve Gizlilik',
          paragraphs: [
            'Yüklenen içerik, istenen hizmeti sunmak için işlenir. Ayrıntılar için Gizlilik Politikası’nı inceleyin.'
          ],
          link: {
            text: 'Gizlilik Politikası',
            href: '/privacy'
          }
        },
        {
          title: '5. Abonelikler ve Ödemeler',
          paragraphs: [
            'Premium abonelikler Google Play üzerinden faturalandırılır. İptal için Google Play → Hesap → Ödemeler ve Abonelikler yolunu kullanabilirsiniz.',
            'İade talepleri Google Play politikalarına göre değerlendirilir.'
          ],
        },
        {
          title: '6. Fikri Mülkiyet',
          paragraphs: [
            'Avenia ve ilişkili içerikler fikri mülkiyet yasalarıyla korunur. Yüklediğiniz içerik üzerinde hak sahibi olduğunuzu veya izniniz olduğunu beyan edersiniz.'
          ],
        },
        {
          title: '7. Hizmet Sınırlamaları',
          paragraphs: [
            'Hizmette kullanım limitleri, dosya boyutu sınırları ve bakım/teknik nedenlerle geçici kesintiler olabilir.'
          ],
        },
        {
          title: '8. Değişiklikler',
          paragraphs: [
            'Şartlar zaman zaman güncellenebilir. Güncellemeler sonrası hizmeti kullanmaya devam etmeniz kabul anlamına gelir.'
          ],
        },
        {
          title: '9. İletişim',
          paragraphs: [
            'Bu şartlar hakkında sorularınız için support@aveniaichat.com adresine ulaşabilirsiniz.'
          ],
        }
      ],
      footerNote: '📄 Bu şartları kabul ederek Avenia’yı güvenli ve adil tutmamıza yardımcı olursunuz.'
    }
  };

  const t = content[lang] || content.en;

  return (
    <div className="min-h-screen bg-[#232323] pt-20">
      <div className="max-w-4xl mx-auto px-6 lg:px-8 py-16">
        {/* Header */}
        <div className="text-center mb-16">
          <div className="w-16 h-16 bg-[#00c896]/20 rounded-2xl flex items-center justify-center mx-auto mb-6">
            <FileText className="w-8 h-8 text-[#00c896]" />
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-6">
            {t.title.split(' ')[0]} <span className="text-[#00c896]">{t.title.split(' ').slice(1).join(' ')}</span>
          </h1>
          <p className="text-xl text-gray-300 max-w-2xl mx-auto">
            {t.subtitle}
          </p>
          <p className="text-gray-400 mt-4">
            {lang === 'tr' ? 'Son güncelleme' : 'Last updated'}: {t.updated}
          </p>
        </div>

        {/* Terms Content */}
        <Card className="bg-gray-800/30 border-gray-700/50 backdrop-blur-sm p-8">
          <div className="prose prose-invert max-w-none">
            {t.sections.map((section) => (
              <div key={section.title}>
                <h2 className="text-2xl font-bold text-white mb-6 border-b border-gray-700 pb-3">
                  {section.title}
                </h2>
                {section.paragraphs?.map((paragraph, index) => (
                  <p key={`${section.title}-p-${index}`} className="text-gray-300 mb-6 leading-relaxed">
                    {paragraph.includes('support@') ? (
                      <>
                        {paragraph.split('support@aveniaichat.com')[0]}
                        <a href="mailto:support@aveniaichat.com" className="text-[#00c896] hover:underline">support@aveniaichat.com</a>
                      </>
                    ) : (
                      paragraph
                    )}
                  </p>
                ))}
                {section.list ? (
                  <ul className="list-disc pl-8 space-y-2 text-gray-300 mb-6">
                    {section.list.map((item) => (
                      <li key={item}>{item}</li>
                    ))}
                  </ul>
                ) : null}
                {section.link ? (
                  <p className="text-gray-300 mb-6">
                    <a href={section.link.href} className="text-[#00c896] hover:underline">
                      {section.link.text}
                    </a>
                  </p>
                ) : null}
              </div>
            ))}

            <div className="bg-[#00c896]/10 border border-[#00c896]/30 rounded-xl p-6 mt-8">
              <p className="text-[#00c896] font-medium">
                {t.footerNote}
              </p>
            </div>
          </div>
        </Card>
      </div>
    </div>
  );
}
